/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_user_pools_id": "us-east-1_zYTpdQhvf",
    "aws_user_pools_web_client_id": "6l0qolmjdpkc1tg1gq8d1v7d8",
};

module.exports = awsmobile;